#1
### Create Completion Time
POST http://localhost:8081/completion-times/create
Content-Type: application/json

{
  "user": "697299e277073fc8e6a06a60",
  "timeInSeconds": 95
}

#2
### Get All Completion Times
GET http://localhost:8081/completion-times/getAll

#3
### Update Completion Time
PUT http://localhost:8081/completion-times/update/69a1ddcd0ed712fb16b534fb
Content-Type: application/json

{
  "timeInSeconds": 45
}
#4
### Delete Completion Time
DELETE http://localhost:8081/completion-times/delete/69a1ddcd0ed712fb16b534fb