import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import '../../css/landingPage.css';

const COLORS = {
  bg: '#0e090b',
  surface: '#1a1118',
  surfaceHover: '#221520',
  red: '#dc2626',
  redHover: '#b91c1c',
  textPrimary: '#f5f0f2',
  textMuted: '#a89aa2',
  border: '#2e1f28',
};

const features = [
  {
    icon: '🎬',
    title: 'Movie Search & Details',
    desc: 'Search any film and dive into cast, plot, ratings, and more — all in one place.',
  },
  {
    icon: '🤖',
    title: 'AI-Powered Reviews',
    desc: 'Get instant, intelligent reviews generated by Google Gemini for any movie.',
  },
  {
    icon: '💬',
    title: 'Movie Chat',
    desc: 'Ask anything about a film and get sharp, conversational answers from an AI that knows the movie inside out.',
  },
  {
    icon: '🍿',
    title: 'Cinema Search',
    desc: 'Find nearby cinemas and showtimes so you can catch the latest releases.',
  },
  {
    icon: '🏆',
    title: 'Game Page',
    desc: 'Test your movie knowledge with interactive challenges.',
  },
];

const styles = {
  root: {
    fontFamily: "'Outfit', 'Source Sans 3', sans-serif",
    background: COLORS.bg,
    color: COLORS.textPrimary,
    minHeight: '100vh',
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    padding: '24px 48px',
    display: 'flex',
    alignItems: 'center',
  },
  logo: {
    fontSize: '1.4rem',
    fontWeight: 800,
    letterSpacing: '-0.5px',
    color: COLORS.textPrimary,
    textDecoration: 'none',
  },
  logoAccent: {
    color: COLORS.red,
  },
  heroWrapper: {
    flex: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    textAlign: 'center',
    padding: '80px 24px 64px',
    position: 'relative',
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -60%)',
    width: '600px',
    height: '600px',
    borderRadius: '50%',
    background: 'radial-gradient(circle, rgba(220,38,38,0.18) 0%, transparent 70%)',
    pointerEvents: 'none',
  },
  eyebrow: {
    fontSize: '0.8rem',
    fontWeight: 600,
    letterSpacing: '2px',
    textTransform: 'uppercase',
    color: COLORS.red,
    marginBottom: '20px',
  },
  headline: {
    fontSize: 'clamp(2.4rem, 6vw, 4rem)',
    fontWeight: 800,
    lineHeight: 1.1,
    marginBottom: '20px',
    background: 'linear-gradient(135deg, #f5f0f2 30%, #dc2626 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
    backgroundClip: 'text',
  },
  subheadline: {
    fontSize: '1.1rem',
    color: COLORS.textMuted,
    maxWidth: '480px',
    lineHeight: 1.6,
    marginBottom: '40px',
  },
  ctaRow: {
    display: 'flex',
    gap: '16px',
    flexWrap: 'wrap',
    justifyContent: 'center',
  },
  btnPrimary: (hovered) => ({
    padding: '14px 32px',
    borderRadius: '8px',
    border: 'none',
    background: hovered ? COLORS.redHover : COLORS.red,
    color: '#fff',
    fontFamily: 'inherit',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-block',
    transition: 'background 0.2s',
  }),
  btnSecondary: (hovered) => ({
    padding: '14px 32px',
    borderRadius: '8px',
    border: `1.5px solid ${hovered ? COLORS.textMuted : COLORS.border}`,
    background: 'transparent',
    color: hovered ? COLORS.textPrimary : COLORS.textMuted,
    fontFamily: 'inherit',
    fontSize: '1rem',
    fontWeight: 600,
    cursor: 'pointer',
    textDecoration: 'none',
    display: 'inline-block',
    transition: 'border-color 0.2s, color 0.2s',
  }),
  featuresSection: {
    padding: '64px 24px',
    maxWidth: '900px',
    margin: '0 auto',
    width: '100%',
  },
  featuresGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, 1fr)',
    gap: '20px',
  },
  featureCard: (hovered) => ({
    background: hovered ? COLORS.surfaceHover : COLORS.surface,
    border: `1px solid ${hovered ? COLORS.border : 'transparent'}`,
    borderRadius: '12px',
    padding: '28px 24px',
    cursor: 'default',
    transition: 'background 0.2s, box-shadow 0.2s, transform 0.2s',
    boxShadow: hovered ? '0 8px 32px rgba(220,38,38,0.12)' : 'none',
    transform: hovered ? 'translateY(-4px)' : 'none',
  }),
  featureIcon: {
    fontSize: '2rem',
    marginBottom: '12px',
  },
  featureTitle: {
    fontSize: '1rem',
    fontWeight: 700,
    marginBottom: '8px',
    color: COLORS.textPrimary,
  },
  featureDesc: {
    fontSize: '0.9rem',
    color: COLORS.textMuted,
    lineHeight: 1.6,
  },
  footer: {
    padding: '24px',
    textAlign: 'center',
    borderTop: `1px solid ${COLORS.border}`,
    fontSize: '0.82rem',
    color: COLORS.textMuted,
  },
};

const LandingPage = () => {
  const [hoveredBtn, setHoveredBtn] = useState(null);
  const [hoveredCard, setHoveredCard] = useState(null);

  return (
    <div style={styles.root}>
      {/* Header — logo mark only */}
      <header style={styles.header} className="lp-fade-up">
        <span style={styles.logo}>
          Movie<span style={styles.logoAccent}>Now</span>
        </span>
      </header>

      {/* Hero */}
      <section style={styles.heroWrapper}>
        <div className="lp-glow" style={styles.glow} />

        <p style={styles.eyebrow} className="lp-fade-up">
          Your Movie Hub
        </p>
        <h1 style={styles.headline} className="lp-fade-up-delay-1">
          Discover, Learn &amp; Master Movies
        </h1>
        <p style={styles.subheadline} className="lp-fade-up-delay-2">
          Search any film, read AI-powered reviews, chat about movies with an AI, find cinemas near you, and challenge yourself — all in one place.
        </p>

        <div style={styles.ctaRow} className="lp-fade-up-delay-3">
          <Link
            to="/signup"
            style={styles.btnPrimary(hoveredBtn === 'start')}
            onMouseEnter={() => setHoveredBtn('start')}
            onMouseLeave={() => setHoveredBtn(null)}
          >
            Get Started
          </Link>
          <Link
            to="/login"
            style={styles.btnSecondary(hoveredBtn === 'login')}
            onMouseEnter={() => setHoveredBtn('login')}
            onMouseLeave={() => setHoveredBtn(null)}
          >
            Log In
          </Link>
        </div>
      </section>

      {/* Features grid */}
      <section style={styles.featuresSection}>
        <div style={styles.featuresGrid}>
          {features.map((f, i) => (
            <div
              key={f.title}
              style={{
                ...styles.featureCard(hoveredCard === i),
                ...(features.length % 2 !== 0 && i === features.length - 1 ? { gridColumn: '1 / -1' } : {}),
              }}
              onMouseEnter={() => setHoveredCard(i)}
              onMouseLeave={() => setHoveredCard(null)}
            >
              <div style={styles.featureIcon}>{f.icon}</div>
              <div style={styles.featureTitle}>{f.title}</div>
              <p style={styles.featureDesc}>{f.desc}</p>
            </div>
          ))}
        </div>
      </section>

      <footer style={styles.footer}>
        &copy; {new Date().getFullYear()} MovieNow. All rights reserved.
      </footer>
    </div>
  );
};

export default LandingPage;